# Project language
language: php

# Allows use container-based infrastructure
sudo: false

# Start mysql service
services:
  - mysql

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files

# Matrix to test in every php version
matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.3
    - php: nightly
  allow_failures:
    - php: nightly

# Define an environment variable
env:
  - SYMFONY_VERSION="4.2.*" DB=mysql

# Update composer
before-install:
  - composer self-update

# Install composer dependencies,
# Create database, schema and fixtures
install:
  - composer install
#  - cp .env.dist .env

# Run script
script:
#    - composer validate --strict --no-check-lock

# After a build, send email notification with the build results
notifications:
  email: ivan@devexus.net

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master